import { Chivo_Mono, Bungee, Gelasio } from "next/font/google";
import "./globals.css";

const chivo = Chivo_Mono({
  subsets: ["latin"],
  variable: "--font-chivo-mono",
});
const bungee = Bungee({
  subsets: ["latin"],
  weight: '400',
  variable: "--font-bungee",
});
const gelasio = Gelasio({
  subsets: ["latin"],
  weight: '400',
  variable: "--font-gelasio",
});

export const metadata = {
  title: "Emir Maya - Full Stack Developer",
  description: "Generated by Emir Maya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bungee.className}>{children}</body>
    </html>
  );
}
